// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function useKettle(config) {
  var match = React.useReducer((function (param, msg) {
          return config.update(param[0], msg);
        }), config.init);
  var dispatch = match[1];
  var match$1 = match[0];
  var cmd = match$1[1];
  var model = match$1[0];
  var runFn = config.run;
  if (runFn !== undefined) {
    React.useEffect((function () {
            runFn(cmd, (function (msg) {
                    dispatch(msg);
                  }));
          }), [cmd]);
  }
  var subsFn = config.subscriptions;
  if (subsFn !== undefined) {
    React.useEffect((function () {
            var subscriptions = subsFn(model);
            var cleanups = subscriptions.map(function (sub) {
                  return sub.start(dispatch);
                });
            return (function () {
                      cleanups.forEach(function (cleanup) {
                            cleanup();
                          });
                    });
          }), [subsFn]);
  }
  return [
          model,
          (function (msg) {
              dispatch(msg);
            })
        ];
}

export {
  useKettle ,
}
/* react Not a pure module */
