// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";

var connections = {};

function getConnection(url) {
  return Js_dict.get(connections, url);
}

function setConnection(url, conn) {
  connections[url] = conn;
}

function removeConnection(_url) {
  
}

function createConnection(url) {
  var ws = new WebSocket(url);
  var conn = {
    ws: ws,
    isConnected: false
  };
  var onOpen = function () {
    conn.isConnected = true;
  };
  var onClose = function () {
    conn.isConnected = false;
  };
  var onError = function () {
    conn.isConnected = false;
  };
  ws.onopen = onOpen;
  ws.onclose = onClose;
  ws.onerror = onError;
  setConnection(url, conn);
  return conn;
}

function getOrCreateConnection(url) {
  var conn = Js_dict.get(connections, url);
  if (conn !== undefined && conn.isConnected) {
    return conn;
  } else {
    return createConnection(url);
  }
}

var Manager = {
  connections: connections,
  getConnection: getConnection,
  setConnection: setConnection,
  removeConnection: removeConnection,
  createConnection: createConnection,
  getOrCreateConnection: getOrCreateConnection
};

export {
  Manager ,
}
/* No side effect */
