// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ProxyReactJs from "../utils/proxy-react.js";

function useRef() {
  return React.useRef(undefined);
}

function refGet(r) {
  return r.current;
}

function refSet(r, v) {
  r.current = Caml_option.some(v);
}

function useEffect0(f) {
  React.useEffect(f, []);
}

function createTrackedSelector(prim) {
  return ProxyReactJs.createTrackedSelector(prim);
}

function createTrackedSelectorFromUseStore(useStoreLike) {
  return ProxyReactJs.createTrackedSelector(useStoreLike);
}

export {
  useRef ,
  refGet ,
  refSet ,
  useEffect0 ,
  createTrackedSelector ,
  createTrackedSelectorFromUseStore ,
}
/* react Not a pure module */
