// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Counter from "./components/Counter.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Counter.make, {}),
              className: "max-w-200"
            });
}

var make = App;

export {
  make ,
}
/* Counter Not a pure module */
