// Generated by ReScript, PLEASE EDIT WITH CARE


function trace(initializer, label) {
  return function (set, get, api) {
    console.log("[dev-trace] initializing:", label);
    var wrappedSet = function (updater) {
      var before = get();
      var after = updater(before);
      console.log("[dev-trace] set:", label);
      console.log("before:", before);
      console.log("after:", after);
      return set(function (param) {
                  return after;
                });
    };
    return initializer(wrappedSet, get, api);
  };
}

export {
  trace ,
}
/* No side effect */
