// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Brew from "../Brew.bs.js";
import * as Chai from "rescript-chai/src/Chai.bs.js";
import * as Button from "./Button.bs.js";
import * as CupTest from "./CupTest.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Counter(props) {
  var __count = props.count;
  var count = __count !== undefined ? __count : 0;
  var match = Chai.useKettle({
        update: Brew.update,
        run: Brew.run,
        init: Brew.init(count),
        subs: Brew.subs
      });
  var dispatch = match[1];
  var model = match[0];
  var match$1 = Chai.useCup({
        model: model,
        dispatch: dispatch,
        filter: (function (model) {
            return model.person;
          }),
        infuse: (function (msg) {
            return {
                    TAG: "PersonMsg",
                    _0: msg
                  };
          })
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: model.title,
                      className: "text-2xl font-bold mb-4"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Count: " + String(model.count),
                      className: "text-lg mb-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              children: "Increment",
                              onClick: (function (param) {
                                  dispatch("Increment");
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Set to 12 after 1 second",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "SetAfterDelay",
                                        _0: 1000,
                                        _1: 12
                                      });
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Set count to 10 and log",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "SetLogCount",
                                        _0: 10
                                      });
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Send WebSocket Message",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "SendWebSocketData",
                                        _0: "Boop"
                                      });
                                })
                            })
                      ],
                      className: "flex flex-wrap"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              children: "Save count to storage",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "SaveCount",
                                        _0: model.count
                                      });
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Load count from storage",
                              onClick: (function (param) {
                                  dispatch("LoadCount");
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Save count to IndexedDB",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "SaveCountIDB",
                                        _0: model.count
                                      });
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Load count from IndexedDB",
                              onClick: (function (param) {
                                  dispatch("LoadCountIDB");
                                })
                            })
                      ],
                      className: "flex flex-wrap"
                    }),
                JsxRuntime.jsx(CupTest.make, {
                      model: match$1[0],
                      dispatch: match$1[1]
                    })
              ]
            });
}

var make = Counter;

export {
  make ,
}
/* Chai Not a pure module */
