// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Brew from "../Brew.bs.js";
import * as Chai from "rescript-chai/src/Chai.bs.js";
import * as Button from "./Button.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function CupTest(props) {
  var match = Brew.usePerson();
  var dispatch = match[1];
  var store = match[0];
  console.log("CupTest rendered --");
  var name = Chai.select(store, (function (m) {
          return m.name;
        }));
  var age = Chai.select(store, (function (m) {
          return m.age;
        }));
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h3", {
                      children: "Cup Test Component",
                      className: "text-xl font-bold mb-4"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Person Name: " + name,
                      className: "text-lg"
                    }),
                JsxRuntime.jsx("p", {
                      children: "Person Age: " + String(age),
                      className: "text-lg mb-4"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              children: "Set Name to Alex",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "UpdateName",
                                        _0: "Alex"
                                      });
                                })
                            }),
                        JsxRuntime.jsx(Button.make, {
                              children: "Set Age to 20",
                              onClick: (function (param) {
                                  dispatch({
                                        TAG: "UpdateAge",
                                        _0: 20
                                      });
                                })
                            })
                      ],
                      className: "flex flex-wrap"
                    })
              ]
            });
}

var make = CupTest;

export {
  make ,
}
/* Brew Not a pure module */
