// Generated by ReScript, PLEASE EDIT WITH CARE


function contains(list, str) {
  var _i = 0;
  while(true) {
    var i = _i;
    if (i >= list.length) {
      return false;
    }
    if (list.item(i) === str) {
      return true;
    }
    _i = i + 1 | 0;
    continue ;
  };
}

export {
  contains ,
}
/* No side effect */
