// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProxyJs from "../utils/proxy.js";

function createTrackedSelector(prim) {
  return ProxyJs.createTrackedSelector(prim);
}

export {
  createTrackedSelector ,
}
/* ../utils/proxy.js Not a pure module */
