// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ProxyReactJs from "../utils/proxy-react.js";

function createTrackedSelector(prim) {
  return ProxyReactJs.createTrackedSelector(prim);
}

export {
  createTrackedSelector ,
}
/* ../utils/proxy-react.js Not a pure module */
