// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Zustand from "zustand";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function useZustandRedux(update, initialModel, initialCmd) {
  var storeRef = React.useRef(undefined);
  if (storeRef.current === undefined) {
    var storeInstance = Zustand.create(function (set, _get, _api) {
          return {
                  state: initialModel,
                  dispatch: (function (action) {
                      set(function (current) {
                            var match = update(current.state, action);
                            return {
                                    state: match[0],
                                    dispatch: current.dispatch,
                                    command: match[1]
                                  };
                          });
                    }),
                  command: initialCmd
                };
        });
    storeRef.current = Caml_option.some(storeInstance);
  }
  var store = storeRef.current;
  var dispatch = Zustand.useStore(store, (function (storeState) {
          return storeState.dispatch;
        }));
  return [
          store,
          dispatch
        ];
}

function createZustandRedux(update, initialModel, initialCmd) {
  return Zustand.create(function (set, _get, _api) {
              return {
                      state: initialModel,
                      dispatch: (function (action) {
                          set(function (current) {
                                var match = update(current.state, action);
                                return {
                                        state: match[0],
                                        dispatch: current.dispatch,
                                        command: match[1]
                                      };
                              });
                        }),
                      command: initialCmd
                    };
            });
}

export {
  useZustandRedux ,
  createZustandRedux ,
}
/* react Not a pure module */
