// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function update(model, msg) {
  if (typeof msg !== "object") {
    return {
            title: model.title,
            expanded: !model.expanded
          };
  } else {
    return {
            title: msg._0,
            expanded: model.expanded
          };
  }
}

function Card(props) {
  var __children = props.children;
  var __expanded = props.expanded;
  var __title = props.title;
  var title = __title !== undefined ? __title : "Default Title";
  var expanded = __expanded !== undefined ? __expanded : false;
  var children = __children !== undefined ? Caml_option.valFromOption(__children) : null;
  var match = React.useReducer(update, {
        title: title,
        expanded: expanded
      });
  var dispatch = match[1];
  var model = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: title
                    }),
                model.expanded ? children : null,
                JsxRuntime.jsx("p", {
                      children: model.expanded ? "Click to collapse" : "Click to expand",
                      style: {
                        color: "#666",
                        fontSize: "0.8em"
                      }
                    })
              ],
              className: "rescript-card",
              style: {
                cursor: "pointer"
              },
              onClick: (function (param) {
                  dispatch("Toggle");
                })
            });
}

var make = Card;

var $$default = Card;

export {
  update ,
  make ,
  $$default as default,
}
/* react Not a pure module */
