// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Counter from "./Counter.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function Nested(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Nested Component"
                    }),
                JsxRuntime.jsx(Counter.make, {
                      count: 20
                    })
              ]
            });
}

var make = Nested;

var $$default = Nested;

export {
  make ,
  $$default as default,
}
/* Counter Not a pure module */
