// Generated by ReScript, PLEASE EDIT WITH CARE

import * as RegistryJs from "./registry.js";

function _register(prim0, prim1) {
  RegistryJs.register(prim0, prim1);
}

function _lookup(prim) {
  return RegistryJs.lookup(prim);
}

function _unregister(prim) {
  return RegistryJs.unregister(prim);
}

function register(dispatch, raw, chrono) {
  var obj = {};
  Object.assign(obj, {
        raw: raw,
        chrono: chrono
      });
  RegistryJs.register(dispatch, obj);
}

function lookup(dispatch) {
  var obj = RegistryJs.lookup(dispatch);
  if (!(obj == null)) {
    return [
            obj.raw,
            obj.chrono
          ];
  }
  
}

function unregister(dispatch) {
  return RegistryJs.unregister(dispatch);
}

export {
  _register ,
  _lookup ,
  _unregister ,
  register ,
  lookup ,
  unregister ,
}
/* ./registry.js Not a pure module */
