// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zustand from "zustand";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Middleware from "zustand/middleware";

function select(store, selector) {
  return Zustand.useStore(store, (function (storeState) {
                return selector(storeState.state);
              }));
}

function makeFilteredStore(origStore, filterOpt, infuseOpt) {
  var getState = function () {
    var s = origStore.getState();
    var statePart = filterOpt !== undefined ? filterOpt(s.state) : s.state;
    var dispatchPart = infuseOpt !== undefined ? (function (subMsg) {
          s.dispatch(infuseOpt(subMsg));
        }) : (function (subMsg) {
          s.dispatch(subMsg);
        });
    return {
            state: statePart,
            dispatch: dispatchPart,
            command: s.command
          };
  };
  var subscribe = function (listener) {
    return origStore.subscribe(function (s) {
                var statePart = filterOpt !== undefined ? filterOpt(s.state) : s.state;
                var dispatchPart = infuseOpt !== undefined ? (function (subMsg) {
                      s.dispatch(infuseOpt(subMsg));
                    }) : (function (subMsg) {
                      s.dispatch(subMsg);
                    });
                listener({
                      state: statePart,
                      dispatch: dispatchPart,
                      command: s.command
                    });
              });
  };
  return {
          getState: getState,
          subscribe: subscribe
        };
}

function brew(config) {
  var storeRef = {
    contents: undefined
  };
  var ensureStore = function () {
    var s = storeRef.contents;
    if (s !== undefined) {
      return Caml_option.valFromOption(s);
    }
    var match = config.init;
    var initialCmd = match[1];
    var initialModel = match[0];
    var initializer = function (set, _get, _api) {
      return {
              state: initialModel,
              dispatch: (function (action) {
                  set(function (current) {
                        var match = config.update(current.state, action);
                        return {
                                state: match[0],
                                dispatch: current.dispatch,
                                command: match[1]
                              };
                      });
                }),
              command: initialCmd
            };
    };
    var ext = config.extend;
    var enhancedInit = ext !== undefined ? ext(initializer) : initializer;
    var s$1 = Zustand.create(enhancedInit);
    var runFn = config.run;
    if (runFn !== undefined) {
      var state0 = s$1.getState();
      var prevCmdRef = {
        contents: state0.command
      };
      runFn(state0.command, state0.dispatch);
      s$1.subscribe(function (st) {
            if (Caml_obj.notequal(st.command, prevCmdRef.contents)) {
              prevCmdRef.contents = st.command;
              runFn(st.command, st.dispatch);
              return ;
            }
            
          });
    }
    var subsFn = config.subs;
    if (subsFn !== undefined) {
      var stateNow = s$1.getState();
      var modelNow = stateNow.state;
      var subscriptions = subsFn(modelNow);
      subscriptions.map(function (sub) {
            return sub.start(stateNow.dispatch);
          });
    }
    storeRef.contents = Caml_option.some(s$1);
    return s$1;
  };
  return function () {
    var store = ensureStore();
    var dispatch = Zustand.useStore(store, (function (st) {
            return st.dispatch;
          }));
    return [
            store,
            dispatch
          ];
  };
}

function pour(useInstanceHook, opts) {
  return function () {
    var match = useInstanceHook();
    var dispatch = match[1];
    var filtered = makeFilteredStore(match[0], opts.filter, opts.infuse);
    var wrappedDispatch = function (subMsg) {
      dispatch(opts.infuse(subMsg));
    };
    return [
            filtered,
            wrappedDispatch
          ];
  };
}

function persist(prim0, prim1) {
  return Middleware.persist(prim0, prim1);
}

function devtools(prim0, prim1) {
  return Middleware.devtools(prim0, prim1);
}

export {
  select ,
  makeFilteredStore ,
  brew ,
  pour ,
  persist ,
  devtools ,
}
/* zustand Not a pure module */
