// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Connection from "./utils/Connection.bs.js";

function listen(_url, cons) {
  return {
          start: (function (dispatch) {
              var conn = Connection.Manager.getOrCreateConnection(_url);
              var messageHandler = function ($$event) {
                dispatch(cons($$event.data));
              };
              conn.ws.onmessage = messageHandler;
              return function () {
                conn.ws.onmessage = (function (param) {
                    
                  });
              };
            })
        };
}

var $$WebSocket = {
  listen: listen
};

function every(interval, cons) {
  return {
          start: (function (dispatch) {
              var timerCallback = function () {
                dispatch(cons());
              };
              var id = setInterval(timerCallback, interval);
              return function () {
                clearInterval(id);
              };
            })
        };
}

var Time = {
  every: every
};

function on(on$1, cons) {
  return {
          start: (function (dispatch) {
              var handler = function ($$event) {
                dispatch(cons($$event));
              };
              var $$window = window;
              $$window.addEventListener(on$1, handler);
              return function () {
                $$window.removeEventListener(on$1, handler);
              };
            })
        };
}

var Events = {
  on: on
};

var Browser = {
  Events: Events
};

export {
  $$WebSocket ,
  Time ,
  Browser ,
}
/* No side effect */
